messages/config/routes.rb
Messages::Application.routes.draw do
  # get "ships/index"
  # get "ships/create"
  # get "ships/show"
  # get "ships/update"
  # get "ships/edit"
  # get "ships/destroy"
  # get "ships/new"
  # get "ships/salute"
  resources :messages
  # get '/messages', to: "messages#index"
  # get '/messages/:id', to: "messages#show"

  # get '/messages/new', to: "messages#new"
  # post '/messages/new', to: "messages#create"

  # get '/messages/:id/edit', to: "messages#edit", as: "messages_edit"
  # put '/messages/:id', to: "messages#update", as: "message"

  # delete '/messages/:id', to: "messages#destroy"

  root to: "messages#index"
end

messages/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :person
  def shorten!
    self.content = self.content[0..119]
  end

  def remove_profanity
    ['bad word', 'another bad word','and another' ].each do |profanity|
      self.content.gsub!("#{profanity}", "")
    end
  end

  def add_smiles
    return if content.empty?
    self.content << ":)"
  end
end

messages/app/models/person.rb
class Person < ActiveRecord::Base
  has_many :messages
end

messages/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.



  protect_from_forgery with: :exception
end

messages/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find_by_id(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.create( content: params[:message][:content])
    redirect_to root_path
  end

  def edit
    @message = Message.find_by_id(params[:id])
  end

  def update
    @message = Message.find_by_id(params[:id])
    @message.content = params[:message][:content]
    @message.save
    redirect_to root_path
  end

  def destroy
    @message = Message.find_by_id(params[:id])
    @message.destroy
    redirect_to root_path
  end
end

messages/app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  def index
  end

  def create
  end

  def show
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def new
  end

  def salute
  end
end

messages/app/helpers/application_helper.rb
module ApplicationHelper
end

messages/app/helpers/messages_helper.rb
module MessagesHelper
end

messages/app/helpers/ships_helper.rb
module ShipsHelper
end

messages/app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

messages/app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

messages/app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

messages/app/views/messages/edit.html.erb
<div class ="row">
  <div class = "large-7 columns large-centered">
    <div class = "panel">
      <%= form_for @message, url: message_path(@message) do |message| %>
        <%= message.text_field :content, placeholder: "message content" %>
        <%= message.submit value: "save edits", class: "button small radius success" %>
      <% end %>
    </div>
  </div>
</div>

messages/app/views/messages/index.html.erb
<div class="row">
  <div class="large-3 large-centered columns">
    <h2>iMessage</h2>
  </div>
</div>



<div class ="row">
  <div class = "large-10 columns large-centered">
    <div class = "panel">
      <% @messages.each do |message| %>
        <div class= "row">
          <div class = "large-7 columns">
            <h3>
              <%= message.content %>
            </h3>
          </div>
          <div class="large-5 columns">
            <%= link_to "show", message_path(message.id), class: "button tiny radius success"  %>
            <%= link_to "edit", edit_message_path(message.id), class: "button tiny radius success"  %>
            <%= link_to "delete", message_path(message.id), method: "DELETE", class: "button tiny radius alert"  %>
          </div>
        </div>

        <div class = "row">
          <div class = "large-12 columns">
            <h6> <%= message.inspect %> </h6>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-3 large-centered columns">
    <%= link_to "new message", new_message_path, class: "button success radius medium" %>
  </div>
</div>

messages/app/views/messages/new.html.erb
<div class ="row">
  <div class = "large-7 columns large-centered">
    <div class = "panel">
      <%= form_for @message do |new_message| %>
        <%= new_message.text_field :content, placeholder: "message content" %>
        <%= new_message.submit class: "button small radius success" %>
      <% end %>
    </div>
  </div>
</div>

messages/app/views/messages/show.html.erb
<div class="row">
  <div class="large-3 large-centered columns">
    <h2>iMessage</h2>
  </div>
</div>



<div class ="row">
  <div class = "large-10 columns large-centered">
    <div class = "panel">
        <div class= "row">
          <div class = "large-9 columns">
            <h3>
              <%= @message.content %>
            </h3>
          </div>
          <div class="large-3 columns">
            <%= link_to "edit", edit_message_path(@message.id), class: "button tiny radius success"  %>
            <%= link_to "delete", message_path(@message.id), method: "DELETE", class: "button tiny radius alert"  %>
          </div>
        </div>

        <div class = "row">
          <div class = "large-12 columns">
            <h6> <%= @message.inspect %> </h6>
          </div>
        </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="large-3 large-centered columns">
    <%= link_to "new message", new_message_path, class: "button success radius medium" %>
  </div>
</div>

messages/app/views/messages/update.html.erb
<h1>Messages#update</h1>
<p>Find me in app/views/messages/update.html.erb</p>

messages/app/views/ships/create.html.erb
<h1>Ships#create</h1>
<p>Find me in app/views/ships/create.html.erb</p>

messages/app/views/ships/destroy.html.erb
<h1>Ships#destroy</h1>
<p>Find me in app/views/ships/destroy.html.erb</p>

messages/app/views/ships/edit.html.erb
<h1>Ships#edit</h1>
<p>Find me in app/views/ships/edit.html.erb</p>

messages/app/views/ships/index.html.erb
<h1>Ships#index</h1>
<p>Find me in app/views/ships/index.html.erb</p>

messages/app/views/ships/new.html.erb
<h1>Ships#new</h1>
<p>Find me in app/views/ships/new.html.erb</p>

messages/app/views/ships/salute.html.erb
<h1>Ships#salute</h1>
<p>Find me in app/views/ships/salute.html.erb</p>

messages/app/views/ships/show.html.erb
<h1>Ships#show</h1>
<p>Find me in app/views/ships/show.html.erb</p>

messages/app/views/ships/update.html.erb
<h1>Ships#update</h1>
<p>Find me in app/views/ships/update.html.erb</p>